SET SQL_SAFE_UPDATES = 0;
USE hr;
SELECT MAX(SALARY) FROM employees;

SELECT MAX(SALARY) - MIN(SALARY) FROM employees;

SELECT JOB_ID, AVG(SALARY) AS Media FROM employees GROUP BY JOB_ID ORDER BY Media DESC;

SELECT SUM(SALARY) FROM employees;

SELECT MAX(SALARY) AS Maior, MIN(SALARY) AS Menor, 
SUM(SALARY) AS Somatoria, ROUND(AVG(SALARY), 2) AS Media FROM employees;

SELECT COUNT(*) FROM employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) AS SALARIO FROM employees GROUP BY JOB_ID;

SELECT SUM(SALARY) FROM employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) AS Media FROM employees
GROUP BY JOB_ID HAVING JOB_ID <> 'IT_PROG' ORDER BY Media DESC;

SELECT
	DEPARTMENT_ID, 
    COUNT(EMPLOYEE_ID) AS Funcionarios,
	AVG(SALARY) AS Salario
FROM employees 
GROUP BY DEPARTMENT_ID
HAVING Funcionarios > 10;

UPDATE employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, 515, 777);

SELECT PHONE_NUMBER FROM employees;

SELECT * FROM employees
WHERE LENGTH(FIRST_NAME) >= 8;

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM employees;

SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM employees;

SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM employees;

SELECT UCASE(FIRST_NAME) FROM employees;

SELECT LAST_NAME, (HIRE_DATE) FROM employees
WHERE MONTH(HIRE_DATE) = 7;

SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) FROM employees;
